version: '3.2'
services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
